version: 0.1.{build}
configuration: Release
install:
- cd src
- nuget restore
- cd..
cache: packages -> **\packages.config
build:
  project: src\EnttoiJobs.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: src\ClientsState\bin\Release
  name: ClientsState
- path: src\HistoryWriter\bin\Release
  name: HistoryWriter
deploy:
- provider: Environment
  name: EnttoiJobs
  on:
    branch: master
