version: 0.1.{build}
configuration: Release
install:
- cd src
- nuget restore
- cd..
cache: packages -> **\packages.config
build:
  project: src\EnttoiJobs.sln
  parallel: true
  verbosity: minimal
before_package:
- ps: msbuild src\ClientsState\ClientsState.csproj /t:Package /p:PackageLocation=clients-state-package.zip /p:PackageAsSingleFile=True
test: off
artifacts:
- path: src/ClientsState/clients-state-package.zip
  name: clients-state-package
deploy:
- provider: Environment
  name: EnttoiJobs
  on:
    branch: master
