version: 0.0.{build}
configuration: Release
install:
- cd src
- nuget restore
- cd..
cache: packages -> **\packages.config
build:
  project: src\EnttoiJobs.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: src\ClientsState\bin\Release\ClientsState.zip
  name: clientstate-deploy-package
  type: WebDeployPackage
deploy:
- provider: Environment
  name: EnttoiJobs
  on:
    branch: master