version: 0.0.{build}
configuration: Release
install:
- cd src
- nuget restore
- cd..
cache: packages -> **\packages.config
build:
  project: src\EnttoiJobs.sln
  parallel: true
  verbosity: minimal
test: off
